### ISSUE TITLE
Create new commands

### ISSUE THREAD

**Issue by SweeneyToddTheDemonBarber** [jcsaaddupuy/xbmc-client#2]
Hey mate,

I just stumbled into your great program, and I was wondering if there's a way for me to use All the commands from xbmcjson? For example I would like to access my tv shows or search for a channel in my PVR. I imagine I could add some commands in the program, however I don't know where this program has been installed.

**Comment by epleterte** [comment]
$ which xbmc-client
    /usr/local/bin/xbmc-client
